### ISSUE TITLE
[BUG] <Import Resolution Error in npm run dev>

### ISSUE THREAD

**Issue by yasminebenslim** [thecyberworld/TheCyberHUB#738] opened 2024-04-15 11:35 UTC
### Describe the bug

When running npm run dev, I encounter an error related to failed import resolution for "./shellData" in "src/components/Tools/ReverseShell/ShellGenerator.jsx". The error message indicates that the file cannot be resolved.

### To Reproduce

Clone the repository.
Navigate to the project directory.
Run npm install to install dependencies.
Run npm run dev.
Observe the error message regarding the failed import resolution for "./shellData".

### Expected Behavior

When running npm run dev, the project should build and serve without encountering any import resolution errors.

### Screenshot/ Video

![Capture d'écran 2024-04-15 122256](https://github.com/thecyberworld/TheCyberHUB/assets/82983299/528937df-7c5c-4edc-ad0e-38009e2045e9)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ArkadiK94** [comment] 2024-04-15 11:47
@yasminebenslim hmm, it is not a bug. You antivirus deleted this file because it thinks that this file is dangerous. Comment the line and continue...

**Comment by ArkadiK94** [comment] 2024-04-15 11:49
Related to issue #613

@kabir0x23 is there a solution or should we close this issue?

**Comment by yasminebenslim** [comment] 2024-04-15 11:50
okay, thank you.

**Comment by yasminebenslim** [comment] 2024-04-15 11:58
@ArkadiK94  The issue was resolved by removing the line "import { ShellCommands, CommandType } from "./shellData";".

**Comment by ArkadiK94** [comment] 2024-04-15 12:07
@yasminebenslim yes, but don't commit it because we need this line in production.

**Comment by ArkadiK94** [comment] 2024-04-15 12:07
I am closing this issue for not because it is not a bug

**Closed** 2024-04-15 12:07 UTC
