### ISSUE TITLE
Interface Freezes when trying to create an empty feed.

### ISSUE THREAD

**Issue by Jazzxe** [thecyberworld/TheCyberHUB#788] opened 2024-05-10 16:37 UTC
### Describe the bug

 When trying to create a an empty feed, after clicking the following section, the application freezes with a message appearing at the bottom right saying "Please enter some content" . A restart is needed in order to be able to interact with the interface again.

### To Reproduce

1- Go to Feeds
2 - Click on "Following" section
3- Click on create feed while its empty

### Expected Behavior
An indicator or a message spawns to clarify that some should be written in the text box.

### Screenshot/ Video

![Screenshot 2024-05-10 173517](https://github.com/thecyberworld/TheCyberHUB/assets/149386123/1fee19dc-1e7a-4eff-9543-d8bdb4585252)
![Screenshot 2024-05-10 173418](https://github.com/thecyberworld/TheCyberHUB/assets/149386123/a0082f8f-4f6e-48b7-a0b2-693ec4970245)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ArkadiK94** [comment] 2024-05-11 12:43
@Jazzxe 
![image](https://github.com/thecyberworld/TheCyberHUB/assets/76536506/65143593-69b5-46b7-ab10-cd26b554cd02)

From the navbar, it looks that you didn't sync the updated changes.

I could not reproduce this bug, you should sync the last changes. open this issue again if it is still happens to you. I will close it for now.

https://github.com/thecyberworld/TheCyberHUB/assets/76536506/eb6ab026-e83d-4931-831e-09c47aeaa944

**Closed** 2024-05-11 12:43 UTC
